name: Linting application
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - run: yarn
      - name: Lint application
      - run: yarn lint
      - name: Build application
      - run: vite build